### ISSUE TITLE
Its not worked !

### ISSUE THREAD

**Issue by ErfanDL** [projetsdiy/ESP8266WebServer-Bootstrap-Bootswatch#1]
Hi. I upload the code to my nodemcu esp8266 but nothing happen after uploading just blinking esp8266 blue led. I changed the ssid and password to my wifi networked but not worked

**Comment by projetsdiy** [comment]
Hi. Did you open the serial monitor to check if the ESP8266 is correctly connected to your WiFi network ? Did you connect a BMP180 ? If no, the program can not continue. If all is ok, you'll have the message 'HTTP server started' with the ip address. So, open a browser and go to this IP to access the web interface of the ESP8266. Tell me if all is clear enough. Have a good day. Christophe

**Comment by ErfanDL** [comment]
Oh sorry man. I dont have a BMP180. is anyway to working without BMP180 ?
thanks

**Comment by projetsdiy** [comment]
No problem ! Yes of course. You just need to comment all lines that call BMP180 : from 223 to 228 and 253. Normally it's enough. Have a good day !

**Comment by ErfanDL** [comment]
thanks my friend's. its worked like a charm 

![snap2](https://cloud.githubusercontent.com/assets/14868771/24245787/f251a744-0fe1-11e7-9cc0-c0f15415e6d4.jpg)


sorry I'm editing your html codes because I dont need sensors.
thanks

**Comment by projetsdiy** [comment]
You're welcome. I'm really happy. I hope to see you again on next project !
